// Generate a typed TypeScript client from schema introspection.
//
// Produces a single self-contained .ts file the user can drop into any
// frontend. The generated module exports:
//   - `Database` — a per-table Row / Insert / Update type map
//   - `createPlutoClient({ url, apiKey, getToken? })` — a minimal fetch
//     wrapper with per-table `list / get / insert / update / remove`
//     helpers whose argument shapes are derived from the schema.
//
// This is a UX helper only. The runtime code emitted here is intentionally
// dependency-free and does not import from `@pluto/client` so users can
// use it without installing anything.

import type { SchemaColumn, SchemaEndpoint, SchemaTable } from "./live";

// Map Postgres udt_name → TS type. Anything unknown falls back to `unknown`
// which forces the developer to narrow explicitly at the call site.
function tsType(col: SchemaColumn): string {
  const t = col.udt_name.toLowerCase();
  let base: string;
  if (["int2","int4","int8","numeric","float4","float8","money"].includes(t)) base = "number";
  else if (t === "bool") base = "boolean";
  else if (t === "json" || t === "jsonb") base = "unknown";
  else if (t === "uuid" || t === "text" || t.startsWith("varchar") || t === "bpchar" || t === "citext") base = "string";
  else if (t.startsWith("timestamp") || t === "date" || t === "time" || t === "timetz") base = "string";
  else if (t.endsWith("[]")) base = "unknown[]";
  else base = "string";
  return col.is_nullable ? `${base} | null` : base;
}

function pascal(s: string): string {
  return s
    .replace(/[^A-Za-z0-9]+/g, "_")
    .split("_")
    .filter(Boolean)
    .map((p) => p[0].toUpperCase() + p.slice(1))
    .join("");
}

function safeKey(s: string): string {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(s) ? s : JSON.stringify(s);
}

function tableTypes(t: SchemaTable): string {
  const name = pascal(t.name);
  const rows = t.columns.map((c) => `  ${safeKey(c.name)}: ${tsType(c)};`).join("\n");
  const inserts = t.columns
    .filter((c) => !c.is_primary_key || !c.has_default)
    .map((c) => {
      const optional = c.has_default || c.is_nullable;
      return `  ${safeKey(c.name)}${optional ? "?" : ""}: ${tsType(c)}${optional && !c.is_nullable ? " | undefined" : ""};`;
    }).join("\n");
  const updates = t.columns.map((c) => `  ${safeKey(c.name)}?: ${tsType(c)};`).join("\n");
  return [
    `export interface ${name}Row {`, rows, `}`,
    ``,
    `export interface ${name}Insert {`, inserts, `}`,
    ``,
    `export interface ${name}Update {`, updates, `}`,
    ``,
  ].join("\n");
}

export function generateTypedClient(input: {
  tables: SchemaTable[];
  endpoints: SchemaEndpoint[];
  baseUrl: string;
  workspaceSlug?: string;
}): string {
  const { tables, endpoints, baseUrl, workspaceSlug } = input;
  const usable = endpoints
    .map((e) => ({ ep: e, tbl: tables.find((t) => t.name === e.table) }))
    .filter((r): r is { ep: SchemaEndpoint; tbl: SchemaTable } => !!r.tbl);

  const typeBlocks = usable.map(({ tbl }) => tableTypes(tbl)).join("\n");

  const dbMap = usable
    .map(({ tbl }) => `  ${safeKey(tbl.name)}: { Row: ${pascal(tbl.name)}Row; Insert: ${pascal(tbl.name)}Insert; Update: ${pascal(tbl.name)}Update };`)
    .join("\n");

  const tableHelpers = usable.map(({ ep, tbl }) => {
    const name  = pascal(tbl.name);
    const path  = ep.base; // e.g. /rest/v1/posts
    const key   = safeKey(tbl.name);
    const pk    = ep.primary_key[0] ?? "id";
    return `
    ${key}: {
      list: (q: ListQuery = {}) => http<${name}Row[]>(\`${path}\` + toQuery(q)),
      get: (id: ${name}Row[${JSON.stringify(pk)}]) =>
        http<${name}Row[]>(\`${path}?${pk}=eq.\` + encodeURIComponent(String(id))).then(r => r[0] ?? null),
      insert: (row: ${name}Insert | ${name}Insert[]) =>
        http<${name}Row[]>(\`${path}\`, { method: "POST", body: JSON.stringify(row), headers: { Prefer: "return=representation" } }),
      update: (id: ${name}Row[${JSON.stringify(pk)}], patch: ${name}Update) =>
        http<${name}Row[]>(\`${path}?${pk}=eq.\` + encodeURIComponent(String(id)), { method: "PATCH", body: JSON.stringify(patch), headers: { Prefer: "return=representation" } }),
      remove: (id: ${name}Row[${JSON.stringify(pk)}]) =>
        http<${name}Row[]>(\`${path}?${pk}=eq.\` + encodeURIComponent(String(id)), { method: "DELETE" }),
    },`;
  }).join("");

  return `// AUTO-GENERATED by Pluto dashboard on ${new Date().toISOString()}
// Base URL: ${baseUrl}${workspaceSlug ? `\n// Workspace: ${workspaceSlug}` : ""}
// Do not edit by hand — regenerate from Dashboard → REST endpoints.
/* eslint-disable */

${typeBlocks}

export interface Database {
${dbMap}
}

export interface PlutoClientOptions {
  /** Base URL of the Pluto instance, e.g. https://api.example.com */
  url?: string;
  /** anon or service_role key (public keys only in browsers). */
  apiKey: string;
  /** Optional user JWT provider for RLS-scoped requests. */
  getToken?: () => string | null | Promise<string | null>;
  /** Global fetch (defaults to window.fetch). */
  fetch?: typeof fetch;
}

export type ListQuery = {
  select?: string;
  order?: string;
  limit?: number;
  offset?: number;
  /** Extra PostgREST filter pairs, e.g. { status: "eq.published" } */
  filter?: Record<string, string | number | boolean>;
};

function toQuery(q: ListQuery): string {
  const p = new URLSearchParams();
  if (q.select) p.set("select", q.select);
  if (q.order)  p.set("order",  q.order);
  if (typeof q.limit  === "number") p.set("limit",  String(q.limit));
  if (typeof q.offset === "number") p.set("offset", String(q.offset));
  if (q.filter) for (const [k, v] of Object.entries(q.filter)) p.set(k, String(v));
  const s = p.toString();
  return s ? "?" + s : "";
}

export function createPlutoClient(opts: PlutoClientOptions) {
  const base = (opts.url ?? ${JSON.stringify(baseUrl)}).replace(/\\/$/, "");
  const doFetch = opts.fetch ?? fetch;

  async function http<T>(path: string, init: RequestInit = {}): Promise<T> {
    const token = opts.getToken ? await opts.getToken() : null;
    const headers: Record<string, string> = {
      "content-type": "application/json",
      "apikey": opts.apiKey,
      ...(init.headers as Record<string, string> | undefined),
    };
    if (token) headers["authorization"] = \`Bearer \${token}\`;
    const res = await doFetch(base + path, { ...init, headers });
    if (!res.ok) {
      const body = await res.text();
      throw new Error(\`\${res.status} \${res.statusText}: \${body}\`);
    }
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  return {
    from: {${tableHelpers}
    },

    // ── Storage helpers (bucket-agnostic, RLS enforced server-side) ──
    // Signed URLs default to short (60s) reads. Set { one_time: true }
    // when handing a URL to an untrusted context so replays are refused.
    storage: {
      /** Single-shot upload (multipart/form-data). ≤ bucket.max_size. */
      upload: async (bucket: string, key: string, file: Blob | File, contentType?: string) => {
        const fd = new FormData();
        fd.append("file", file, (file as File).name ?? "blob");
        const token = opts.getToken ? await opts.getToken() : null;
        const headers: Record<string, string> = { apikey: opts.apiKey };
        if (token) headers["authorization"] = \`Bearer \${token}\`;
        if (contentType) headers["x-content-type"] = contentType;
        const res = await doFetch(\`\${base}/storage/v1/object/\${bucket}/\${encodeURI(key)}\`, {
          method: "POST", headers, body: fd,
        });
        if (!res.ok) throw new Error(\`\${res.status} \${res.statusText}: \${await res.text()}\`);
        return res.json() as Promise<{ bucket: string; key: string; size: number; content_type: string }>;
      },
      /** Streamed download → Blob. */
      download: async (bucket: string, key: string): Promise<Blob> => {
        const token = opts.getToken ? await opts.getToken() : null;
        const headers: Record<string, string> = { apikey: opts.apiKey };
        if (token) headers["authorization"] = \`Bearer \${token}\`;
        const res = await doFetch(\`\${base}/storage/v1/object/\${bucket}/\${encodeURI(key)}\`, { headers });
        if (!res.ok) throw new Error(\`\${res.status} \${res.statusText}\`);
        return res.blob();
      },
      remove: (bucket: string, key: string) =>
        http<{ ok: true }>(\`/storage/v1/object/\${bucket}/\${encodeURI(key)}\`, { method: "DELETE" }),
      signedUrl: (bucket: string, key: string, opts2: { expires_in?: number; mode?: "read" | "write"; one_time?: boolean } = {}) =>
        http<{ url: string; id: string; expires_at: string; one_time: boolean }>(
          \`/storage/v1/object/sign/\${bucket}/\${encodeURI(key)}\`,
          { method: "POST", body: JSON.stringify(opts2) },
        ),
      revokeSignedUrl: (id: string) =>
        http<{ ok: true }>(\`/storage/v1/object/sign/grants/\${encodeURIComponent(id)}\`, { method: "DELETE" }),
      /**
       * Resumable / multipart upload for large files. Splits the file
       * into 5 MiB chunks (configurable) and PUTs them individually,
       * then finalizes with /upload/:id/complete. Server re-checks
       * RLS on every part so a revoked grant kills the session.
       */
      uploadLarge: async (
        bucket: string,
        key: string,
        file: Blob,
        opts2: { part_size?: number; content_type?: string; onProgress?: (done: number, total: number) => void } = {},
      ) => {
        const part_size = opts2.part_size ?? 5 * 1024 * 1024;
        const content_type = opts2.content_type ?? (file as File).type ?? "application/octet-stream";
        const init = await http<{ upload_id: string; part_size: number; part_count: number }>(
          \`/storage/v1/upload/init\`,
          { method: "POST", body: JSON.stringify({ bucket, key, size: file.size, content_type, part_size }) },
        );
        const token = opts.getToken ? await opts.getToken() : null;
        const headers: Record<string, string> = {
          apikey: opts.apiKey, "content-type": "application/octet-stream",
        };
        if (token) headers["authorization"] = \`Bearer \${token}\`;
        const parts: { part_number: number; etag: string }[] = [];
        for (let i = 0; i < init.part_count; i++) {
          const slice = file.slice(i * init.part_size, (i + 1) * init.part_size);
          const res = await doFetch(\`\${base}/storage/v1/upload/\${init.upload_id}/part/\${i + 1}\`, {
            method: "PUT", headers, body: slice,
          });
          if (!res.ok) {
            await doFetch(\`\${base}/storage/v1/upload/\${init.upload_id}/abort\`, { method: "DELETE", headers });
            throw new Error(\`part \${i + 1}: \${res.status} \${await res.text()}\`);
          }
          const j = await res.json() as { part_number: number; etag: string };
          parts.push({ part_number: j.part_number, etag: j.etag });
          opts2.onProgress?.((i + 1) * init.part_size, file.size);
        }
        return http<{ bucket: string; key: string; size: number; content_type: string }>(
          \`/storage/v1/upload/\${init.upload_id}/complete\`,
          { method: "POST", body: JSON.stringify({ parts }) },
        );
      },
    },

    /** Raw request escape hatch. */
    request: http,
  };
}

export type PlutoClient = ReturnType<typeof createPlutoClient>;
`;
}
