// One-click local Docker Compose bundle generator.
//
// Produces a self-contained folder (docker-compose.yml + .env + bootstrap
// script + README) that boots Postgres, MinIO, Mailpit and the Pluto API,
// then runs migrations/import and a first verification pass — all driven
// from the SAME `.env` file so connection, migration and verification never
// drift apart.

export type LocalStackConfig = {
  projectName: string;
  apiPort: number;
  dbPort: number;
  minioPort: number;
  mailpitPort: number;
  dbUser: string;
  dbPassword: string;
  dbName: string;
  jwtSecret: string;
  anonKey: string;
  serviceKey: string;
  frontendOrigin: string;
  /** Optional SQL file (relative to the bundle) applied after migrations. */
  importSqlPath: string;
  withMinio: boolean;
  withMailpit: boolean;
};

export const DEFAULT_LOCAL_STACK: LocalStackConfig = {
  projectName: "pluto-local",
  apiPort: 8787,
  dbPort: 5433,
  minioPort: 9000,
  mailpitPort: 8025,
  dbUser: "pluto",
  dbPassword: "pluto",
  dbName: "pluto",
  jwtSecret: "",
  anonKey: "",
  serviceKey: "",
  frontendOrigin: "http://localhost:5173",
  importSqlPath: "./import.sql",
  withMinio: true,
  withMailpit: true,
};

/** Browser-safe random hex (Web Crypto). */
export function randomHex(bytes: number): string {
  const buf = new Uint8Array(bytes);
  globalThis.crypto.getRandomValues(buf);
  return [...buf].map((b) => b.toString(16).padStart(2, "0")).join("");
}

export function withGeneratedSecrets(cfg: LocalStackConfig): LocalStackConfig {
  return {
    ...cfg,
    jwtSecret: cfg.jwtSecret || randomHex(32),
    anonKey: cfg.anonKey || `pluto_anon_${randomHex(16)}`,
    serviceKey: cfg.serviceKey || `pluto_service_${randomHex(24)}`,
  };
}

export type BundleFile = { path: string; contents: string; language: string };

function envFile(c: LocalStackConfig): string {
  return `# Single source of truth for the local Pluto stack.
# Used by docker-compose.yml, bootstrap.sh (migrations + import) and verify.sh.
COMPOSE_PROJECT_NAME=${c.projectName}

# --- API ---
NODE_ENV=development
PORT=3000
API_PORT=${c.apiPort}
PLUTO_URL=http://localhost:${c.apiPort}
SITE_URL=${c.frontendOrigin}
CORS_ORIGINS=${c.frontendOrigin},http://localhost:3000

# --- Database ---
POSTGRES_USER=${c.dbUser}
POSTGRES_PASSWORD=${c.dbPassword}
POSTGRES_DB=${c.dbName}
DB_PORT=${c.dbPort}
DATABASE_URL=postgres://${c.dbUser}:${c.dbPassword}@db:5432/${c.dbName}
DATABASE_URL_HOST=postgres://${c.dbUser}:${c.dbPassword}@localhost:${c.dbPort}/${c.dbName}

# --- Auth / keys ---
PLUTO_JWT_SECRET=${c.jwtSecret}
JWT_SECRET=${c.jwtSecret}
ANON_KEY=${c.anonKey}
SERVICE_ROLE_KEY=${c.serviceKey}

# --- Frontend (.env of your app) ---
VITE_PLUTO_URL=http://localhost:${c.apiPort}
VITE_PLUTO_ANON_KEY=${c.anonKey}
${c.withMinio ? `
# --- Storage (MinIO) ---
S3_ENDPOINT=http://minio:9000
S3_REGION=us-east-1
S3_ACCESS_KEY=minio
S3_SECRET_KEY=minio1234
S3_BUCKET=pluto
S3_FORCE_PATH_STYLE=1
MINIO_PORT=${c.minioPort}` : ""}${c.withMailpit ? `
# --- Email (Mailpit) ---
SMTP_HOST=mailpit
SMTP_PORT=1025
SMTP_FROM=no-reply@localhost
MAILPIT_PORT=${c.mailpitPort}` : ""}

# --- Bootstrap behaviour ---
PLUTO_MIGRATIONS_DIR=./migrations
PLUTO_IMPORT_SQL=${c.importSqlPath}
PLUTO_VERIFY_ON_BOOT=1
`;
}

function composeFile(c: LocalStackConfig): string {
  const minio = c.withMinio
    ? `
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: \${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: \${S3_SECRET_KEY}
    ports:
      - "\${MINIO_PORT}:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - pluto_s3:/data
`
    : "";
  const mailpit = c.withMailpit
    ? `
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "\${MAILPIT_PORT}:8025"
      - "1025:1025"
`
    : "";
  return `# Generated by Pluto BaaS — one-click local stack.
# Boot everything:  ./bootstrap.sh
# Stop:             docker compose down      (add -v to wipe data)

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: \${POSTGRES_USER}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD}
      POSTGRES_DB: \${POSTGRES_DB}
    ports:
      - "\${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER} -d \${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - pluto_pg:/var/lib/postgresql/data
${minio}${mailpit}
  api:
    image: \${PLUTO_IMAGE:-ghcr.io/pluto-baas/api:latest}
    depends_on:
      db:
        condition: service_healthy${c.withMinio ? `
      minio:
        condition: service_healthy` : ""}
    env_file: .env
    environment:
      DATABASE_URL: \${DATABASE_URL}
    ports:
      - "\${API_PORT}:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/readyz || exit 1"]
      interval: 3s
      timeout: 3s
      retries: 40

volumes:
  pluto_pg: {}${c.withMinio ? `
  pluto_s3: {}` : ""}
`;
}

function bootstrapScript(): string {
  return `#!/usr/bin/env bash
# One command: boot -> connect -> migrate -> import -> verify.
# Everything reads the same .env, so there is no second place to configure.
set -euo pipefail
cd "$(dirname "$0")"

[ -f .env ] || { echo "missing .env — regenerate the bundle"; exit 1; }
set -a; . ./.env; set +a

step() { printf "\\n\\033[1;34m▶ %s\\033[0m\\n" "$*"; }
ok()   { printf "  \\033[32m✔\\033[0m %s\\n" "$*"; }
die()  { printf "  \\033[31m✘\\033[0m %s\\n" "$*" >&2; exit 1; }

step "1/5  starting containers"
docker compose --env-file .env up -d

step "2/5  waiting for the API to become ready"
for i in $(seq 1 60); do
  code=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:\${API_PORT}/readyz" || true)
  [ "$code" = "200" ] && { ok "API ready on port \${API_PORT}"; break; }
  sleep 2
  [ "$i" = "60" ] && die "API never became ready — docker compose logs api"
done

step "3/5  applying migrations (\${PLUTO_MIGRATIONS_DIR})"
if [ -d "\${PLUTO_MIGRATIONS_DIR}" ]; then
  for f in $(ls "\${PLUTO_MIGRATIONS_DIR}"/*.sql 2>/dev/null | sort); do
    echo "   - $(basename "$f")"
    docker compose exec -T db psql -v ON_ERROR_STOP=1 -U "\${POSTGRES_USER}" -d "\${POSTGRES_DB}" < "$f"
  done
  ok "migrations applied"
else
  ok "no migrations directory — skipped"
fi

step "4/5  importing seed/dump (\${PLUTO_IMPORT_SQL})"
if [ -f "\${PLUTO_IMPORT_SQL}" ]; then
  docker compose exec -T db psql -v ON_ERROR_STOP=1 -U "\${POSTGRES_USER}" -d "\${POSTGRES_DB}" < "\${PLUTO_IMPORT_SQL}"
  ok "import applied"
else
  ok "no import file — skipped"
fi

step "5/5  verification"
./verify.sh

printf "\\n\\033[1;32m✅ local stack ready\\033[0m\\n"
printf "   API       http://localhost:\${API_PORT}\\n"
printf "   Postgres  localhost:\${DB_PORT}\\n"
printf "   Frontend  point VITE_PLUTO_URL at http://localhost:\${API_PORT}\\n"
`;
}

function verifyScript(): string {
  return `#!/usr/bin/env bash
# Initial verification — same .env, no extra config.
set -uo pipefail
cd "$(dirname "$0")"
set -a; . ./.env; set +a

pass=0; fail=0
check() {
  local label="$1"; shift
  if "$@" >/dev/null 2>&1; then printf "  \\033[32m✔\\033[0m %s\\n" "$label"; pass=$((pass+1));
  else printf "  \\033[31m✘\\033[0m %s\\n" "$label"; fail=$((fail+1)); fi
}

echo "Verifying \${PLUTO_URL}"
check "health endpoint"    curl -fsS "\${PLUTO_URL}/healthz"
check "readiness (db+jwt)" curl -fsS "\${PLUTO_URL}/readyz"
check "anon key accepted"  curl -fsS -H "apikey: \${ANON_KEY}" "\${PLUTO_URL}/rest/v1/"
check "service key works"  curl -fsS -H "authorization: Bearer \${SERVICE_ROLE_KEY}" "\${PLUTO_URL}/admin/v1/health"
check "database reachable" docker compose exec -T db pg_isready -U "\${POSTGRES_USER}" -d "\${POSTGRES_DB}"
check "CORS origin set"    bash -c '[ -n "\${CORS_ORIGINS:-}" ]'

echo
echo "  passed: $pass   failed: $fail"
[ "$fail" -eq 0 ] || exit 1
`;
}

function readme(c: LocalStackConfig): string {
  return `# ${c.projectName} — local Pluto stack

One command boots everything and verifies it:

\`\`\`bash
chmod +x bootstrap.sh verify.sh
./bootstrap.sh
\`\`\`

## What runs

| Service | URL |
| --- | --- |
| Pluto API | http://localhost:${c.apiPort} |
| Postgres | localhost:${c.dbPort} (${c.dbUser}/${c.dbName}) |
${c.withMinio ? `| MinIO | http://localhost:${c.minioPort} (console :9001) |\n` : ""}${c.withMailpit ? `| Mailpit | http://localhost:${c.mailpitPort} |\n` : ""}
## Single \`.env\`

\`.env\` is the only config file. \`docker-compose.yml\`, \`bootstrap.sh\`
(migrations + import) and \`verify.sh\` all read it, so connection strings,
keys and CORS can never drift between steps.

## Wire your frontend

\`\`\`
VITE_PLUTO_URL=http://localhost:${c.apiPort}
VITE_PLUTO_ANON_KEY=${c.anonKey || "<anon key from .env>"}
\`\`\`

## Migrations & import

- Put \`.sql\` files in \`migrations/\` — applied in filename order.
- Put a Supabase/Postgres dump at \`${c.importSqlPath}\` — applied after migrations.
- Re-run \`./bootstrap.sh\` any time; it is idempotent as long as your SQL is.

## Reset

\`\`\`bash
docker compose down -v && ./bootstrap.sh
\`\`\`
`;
}

export function buildLocalStackBundle(cfg: LocalStackConfig): BundleFile[] {
  return [
    { path: ".env", contents: envFile(cfg), language: "bash" },
    { path: "docker-compose.yml", contents: composeFile(cfg), language: "yaml" },
    { path: "bootstrap.sh", contents: bootstrapScript(), language: "bash" },
    { path: "verify.sh", contents: verifyScript(), language: "bash" },
    { path: "README.md", contents: readme(cfg), language: "markdown" },
  ];
}

export function downloadFile(name: string, contents: string) {
  const blob = new Blob([contents], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}
