// Laravel .env → Pluto BaaS environment mapping.
export type EnvMapEntry = {
  laravel: string;
  pluto: string;
  value: string;      // placeholder like <REQUIRED>, <GENERATE:32>, or copied value
  note?: string;
};

const MAP: Array<[RegExp, (k: string, v: string) => EnvMapEntry | null]> = [
  [/^APP_KEY$/, () => ({ laravel: "APP_KEY", pluto: "PLUTO_JWT_SECRET", value: "<GENERATE:64>", note: "auto-generated on install" })],
  [/^APP_URL$/, (_, v) => ({ laravel: "APP_URL", pluto: "PLUTO_PUBLIC_URL", value: v || "<REQUIRED>" })],
  [/^DB_HOST$/, (_, v) => ({ laravel: "DB_HOST", pluto: "PLUTO_PG_HOST", value: v || "<REQUIRED>" })],
  [/^DB_PORT$/, (_, v) => ({ laravel: "DB_PORT", pluto: "PLUTO_PG_PORT", value: v || "5432" })],
  [/^DB_DATABASE$/, (_, v) => ({ laravel: "DB_DATABASE", pluto: "PLUTO_PG_DATABASE", value: v || "<REQUIRED>" })],
  [/^DB_USERNAME$/, (_, v) => ({ laravel: "DB_USERNAME", pluto: "PLUTO_PG_USER", value: v || "<REQUIRED>" })],
  [/^DB_PASSWORD$/, () => ({ laravel: "DB_PASSWORD", pluto: "PLUTO_PG_PASSWORD", value: "<REQUIRED>" })],
  [/^MAIL_HOST$/, (_, v) => ({ laravel: "MAIL_HOST", pluto: "PLUTO_SMTP_HOST", value: v || "<REQUIRED>" })],
  [/^MAIL_PORT$/, (_, v) => ({ laravel: "MAIL_PORT", pluto: "PLUTO_SMTP_PORT", value: v || "587" })],
  [/^MAIL_USERNAME$/, (_, v) => ({ laravel: "MAIL_USERNAME", pluto: "PLUTO_SMTP_USER", value: v || "<REQUIRED>" })],
  [/^MAIL_PASSWORD$/, () => ({ laravel: "MAIL_PASSWORD", pluto: "PLUTO_SMTP_PASSWORD", value: "<REQUIRED>" })],
  [/^MAIL_FROM_ADDRESS$/, (_, v) => ({ laravel: "MAIL_FROM_ADDRESS", pluto: "PLUTO_SMTP_FROM", value: v || "<REQUIRED>" })],
  [/^AWS_ACCESS_KEY_ID$/, () => ({ laravel: "AWS_ACCESS_KEY_ID", pluto: "PLUTO_STORAGE_ACCESS_KEY", value: "<REQUIRED>" })],
  [/^AWS_SECRET_ACCESS_KEY$/, () => ({ laravel: "AWS_SECRET_ACCESS_KEY", pluto: "PLUTO_STORAGE_SECRET_KEY", value: "<REQUIRED>" })],
  [/^AWS_BUCKET$/, (_, v) => ({ laravel: "AWS_BUCKET", pluto: "PLUTO_STORAGE_BUCKET", value: v || "<REQUIRED>" })],
  [/^AWS_DEFAULT_REGION$/, (_, v) => ({ laravel: "AWS_DEFAULT_REGION", pluto: "PLUTO_STORAGE_REGION", value: v || "us-east-1" })],
  [/^SANCTUM_STATEFUL_DOMAINS$/, (_, v) => ({ laravel: "SANCTUM_STATEFUL_DOMAINS", pluto: "PLUTO_ALLOWED_ORIGINS", value: v || "<REQUIRED>" })],
];

export function mapEnv(envExample: Record<string, string>): { entries: EnvMapEntry[]; unknown: string[] } {
  const entries: EnvMapEntry[] = [];
  const unknown: string[] = [];
  for (const [k, v] of Object.entries(envExample)) {
    let matched = false;
    for (const [re, fn] of MAP) {
      if (re.test(k)) {
        const e = fn(k, v);
        if (e) { entries.push(e); matched = true; break; }
      }
    }
    if (!matched) unknown.push(k);
  }
  return { entries, unknown };
}

export function buildEnvTemplate(entries: EnvMapEntry[], unknown: string[]): string {
  const lines = [
    "# Pluto BaaS environment template — generated by Auto-Connect Studio",
    "# systemd EnvironmentFile-compatible. Store at /etc/pluto-autoconnect.env (mode 0600).",
    "",
  ];
  for (const e of entries) {
    if (e.note) lines.push(`# ${e.note}`);
    lines.push(`# ← ${e.laravel}`);
    lines.push(`${e.pluto}=${e.value}`);
    lines.push("");
  }
  if (unknown.length) {
    lines.push("# ── Unmapped Laravel keys (review manually) ──");
    for (const k of unknown) lines.push(`# TODO: ${k}`);
  }
  return lines.join("\n");
}

export function buildInstallSecretsScript(): string {
  return `#!/usr/bin/env bash
# Install/restore Pluto secrets from template with auto-generation for <GENERATE:N>.
set -euo pipefail
TEMPLATE="\${1:-pluto.env.template}"
TARGET="\${TARGET:-/etc/pluto-autoconnect.env}"
UNIT="\${UNIT:-pluto-backend.service}"

[ -f "$TEMPLATE" ] || { echo "template missing: $TEMPLATE"; exit 1; }
umask 077
tmp="$(mktemp)"
while IFS= read -r line; do
  case "$line" in
    ""|"#"*) echo "$line" >> "$tmp";;
    *=*)
      key="\${line%%=*}"; val="\${line#*=}"
      case "$val" in
        "<GENERATE:"*">"*)
          n="\${val#<GENERATE:}"; n="\${n%%>*}"
          val="$(openssl rand -hex "\$((n/2))")"
          ;;
        "<REQUIRED>")
          if [ -z "\${!key:-}" ]; then
            read -r -p "  $key: " val
          else
            val="\${!key}"
          fi
          ;;
      esac
      echo "$key=$val" >> "$tmp"
      ;;
  esac
done < "$TEMPLATE"
install -m 0600 "$tmp" "$TARGET"
rm -f "$tmp"
echo "✔ wrote $TARGET"
systemctl daemon-reload
systemctl restart "$UNIT" || echo "  (reload $UNIT manually)"
`;
}
