// Convert parsed Laravel TableDefs into Pluto-ready Postgres migration SQL.
// Always emits GRANT + RLS enable + owner policy per the public-schema rule.
import type { TableDef } from "./types";

export function tableToSql(t: TableDef): string {
  const lines: string[] = [];
  lines.push(`-- Table: ${t.name}`);
  lines.push(`CREATE TABLE IF NOT EXISTS public.${q(t.name)} (`);

  const cols: string[] = [];
  const hasId = t.columns.some((c) => c.name === "id");
  if (!hasId) {
    cols.push(`  id uuid PRIMARY KEY DEFAULT gen_random_uuid()`);
  }
  for (const c of t.columns) {
    let line = `  ${q(c.name)} ${c.type}`;
    if (c.primary) line += " PRIMARY KEY";
    if (c.default) line += ` DEFAULT ${wrapDefault(c.default, c.type)}`;
    if (c.nullable === false || c.primary) line += " NOT NULL";
    else if (c.nullable !== true && !c.primary) line += " NOT NULL";
    if (c.unique) line += " UNIQUE";
    if (c.references) {
      line += ` REFERENCES public.${q(c.references.table)}(${q(c.references.column)}) ON DELETE CASCADE`;
    }
    cols.push(line);
  }
  // owner column for RLS if not present
  const hasCol = (name: string) => t.columns.some((c) => c.name === name);
  if (!hasCol("user_id") && !hasCol("owner_id")) {
    cols.push(`  owner_id uuid`);
  }
  if (t.timestamps) {
    if (!hasCol("created_at")) cols.push(`  created_at timestamptz NOT NULL DEFAULT now()`);
    if (!hasCol("updated_at")) cols.push(`  updated_at timestamptz NOT NULL DEFAULT now()`);
  }
  if (t.softDeletes && !hasCol("deleted_at")) {
    cols.push(`  deleted_at timestamptz`);
  }

  lines.push(cols.join(",\n"));
  lines.push(`);`);
  lines.push("");
  // GRANTs (required by public-schema rule)
  lines.push(`GRANT SELECT, INSERT, UPDATE, DELETE ON public.${q(t.name)} TO authenticated;`);
  lines.push(`GRANT ALL ON public.${q(t.name)} TO service_role;`);
  lines.push("");
  // RLS
  lines.push(`ALTER TABLE public.${q(t.name)} ENABLE ROW LEVEL SECURITY;`);
  const ownerCol = t.columns.some((c) => c.name === "user_id") ? "user_id"
    : t.columns.some((c) => c.name === "owner_id") ? "owner_id"
    : "owner_id";
  lines.push(`DROP POLICY IF EXISTS "${t.name}_owner_all" ON public.${q(t.name)};`);
  lines.push(`CREATE POLICY "${t.name}_owner_all" ON public.${q(t.name)}`);
  lines.push(`  FOR ALL TO authenticated`);
  lines.push(`  USING (${q(ownerCol)} = auth.uid())`);
  lines.push(`  WITH CHECK (${q(ownerCol)} = auth.uid());`);
  lines.push("");
  return lines.join("\n");
}

function q(id: string): string {
  return /^[a-z_][a-z0-9_]*$/i.test(id) ? id : `"${id.replace(/"/g, '""')}"`;
}
function wrapDefault(v: string, type: string): string {
  const trimmed = v.trim();
  // Normalize legacy Laravel/uuid-ossp default to pgcrypto's built-in.
  // Prevents "invalid input syntax for type uuid: uuid_generate_v4()" when the
  // uuid-ossp extension is not installed on the target Postgres instance.
  if (/^uuid_generate_v4\s*\(\s*\)$/i.test(trimmed)) return "gen_random_uuid()";
  // Any SQL function call (identifier(...)) or common keyword: pass through unquoted.
  if (/^[a-zA-Z_][\w.]*\s*\([^)]*\)$/.test(trimmed)) return trimmed;
  if (/^(current_timestamp|current_date|current_time|null|true|false)$/i.test(trimmed)) return trimmed;
  if (type.includes("int") || type === "numeric" || type === "double precision" || type === "boolean") return v;
  return `'${v.replace(/'/g, "''")}'`;
}

export function buildMigrationBundle(tables: TableDef[]): string {
  const header = [
    "-- Generated by Auto-Connect Studio",
    `-- Generated at: ${new Date().toISOString()}`,
    "-- Applies to Pluto BaaS (Postgres 15+, RLS enforced).",
    "",
    "BEGIN;",
    "",
  ];

  // Ensure referenced enum types exist before any CREATE TABLE uses them.
  const preamble: string[] = [];
  const usesAppRole = tables.some((t) =>
    t.columns.some((c) => /\bapp_role\b/i.test(c.type))
  );
  if (usesAppRole) {
    preamble.push(
      `DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_role') THEN
    CREATE TYPE public.app_role AS ENUM ('admin', 'moderator', 'user');
  END IF;
END $$;`,
      ""
    );
  }

  const footer = ["COMMIT;", ""];
  return [...header, ...preamble, ...tables.map(tableToSql), ...footer].join("\n");
}
