import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  splitSqlStatements,
  convertMysqlStatement,
  detectDialect,
} from '../src/dbio/mysql-to-pg.js';

describe('splitSqlStatements', () => {
  it('splits on ; and skips semicolons inside strings', () => {
    const s = splitSqlStatements(`SELECT 'a;b'; SELECT 1; -- x;\nSELECT 2;`);
    assert.deepEqual(s, [`SELECT 'a;b'`, 'SELECT 1', '-- x;\nSELECT 2']);
  });

  it('respects backtick identifiers', () => {
    assert.deepEqual(splitSqlStatements('SELECT `a;b` FROM t;'), ['SELECT `a;b` FROM t']);
  });

  it('handles DELIMITER directive', () => {
    const s = splitSqlStatements(
      `DELIMITER //\nCREATE PROCEDURE p() BEGIN SELECT 1; END//\nDELIMITER ;\nSELECT 2;`
    );
    assert.equal(s.length, 2);
    assert.match(s[0], /CREATE PROCEDURE/);
    assert.equal(s[1], 'SELECT 2');
  });

  it('handles dollar-quoted blocks', () => {
    const s = splitSqlStatements(`CREATE FUNCTION f() RETURNS int AS $$ BEGIN RETURN 1; END $$ LANGUAGE plpgsql;`);
    assert.equal(s.length, 1);
  });
});

describe('convertMysqlStatement', () => {
  it('drops SET FOREIGN_KEY_CHECKS', () => {
    assert.equal(convertMysqlStatement('SET FOREIGN_KEY_CHECKS=0'), null);
  });
  it('strips ENGINE / CHARSET tail', () => {
    const r = convertMysqlStatement(
      'CREATE TABLE `t` (`id` int AUTO_INCREMENT PRIMARY KEY) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4'
    )!;
    assert.doesNotMatch(r, /ENGINE|CHARSET|InnoDB/i);
    assert.match(r, /GENERATED BY DEFAULT AS IDENTITY/);
    assert.match(r, /"t"/);
    assert.match(r, /"id"/);
  });
  it('maps types', () => {
    const r = convertMysqlStatement(
      'CREATE TABLE t (a tinyint(1), b datetime, c longtext, d json, e int unsigned)'
    )!;
    assert.match(r, /boolean/);
    assert.match(r, /timestamptz/);
    assert.match(r, /text/);
    assert.match(r, /jsonb/);
    assert.match(r, /bigint/);
  });
  it('drops KEY/INDEX inside CREATE TABLE', () => {
    const r = convertMysqlStatement(
      'CREATE TABLE t (id int, name text, KEY `name_idx` (`name`), UNIQUE KEY `u` (`id`))'
    )!;
    assert.doesNotMatch(r, /\bKEY\b/i);
    assert.doesNotMatch(r, /,\s*\)/);
  });
  it('converts INSERT IGNORE and REPLACE', () => {
    assert.match(convertMysqlStatement("INSERT IGNORE INTO t VALUES (1)")!, /^INSERT INTO/);
    assert.match(convertMysqlStatement("REPLACE INTO t VALUES (1)")!, /^INSERT INTO/);
  });
  it('strips ON UPDATE CURRENT_TIMESTAMP', () => {
    const r = convertMysqlStatement(
      'CREATE TABLE t (updated_at datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)'
    )!;
    assert.doesNotMatch(r, /ON UPDATE/i);
  });
});

describe('detectDialect', () => {
  it('detects mysql', () => {
    assert.equal(detectDialect('CREATE TABLE `t` (`id` int) ENGINE=InnoDB'), 'mysql');
  });
  it('detects postgres', () => {
    assert.equal(detectDialect('-- pg_dump 15.3\nCREATE TABLE t (id int)'), 'postgres');
  });
});
