#!/usr/bin/env bash
# inject-pluto-env.sh
# ---------------------------------------------------------------
# Writes dist/env.js (window.__PLUTO_ENV__) from VITE_PLUTO_URL /
# VITE_PLUTO_ANON_KEY so the built bundle always has a runtime API
# URL + anon key regardless of how it was built. Also injects the
# <script src="/env.js"></script> tag into dist/index.html if missing.
# As a cutover convenience, it also removes stale Supabase dns-prefetch /
# preconnect <link> hints from built HTML only. It does NOT remove real
# Supabase API usage from JS; assert-no-supabase.sh still fails those.
#
# Usage:
#   VITE_PLUTO_URL=https://api.timescard.cloud \
#   VITE_PLUTO_ANON_KEY=pk_anon_xxx \
#     bash pluto-backend/deploy/inject-pluto-env.sh [dist_dir]
#
# Defaults dist_dir to ./dist. Exits non-zero if either var is empty.
set -euo pipefail

DIST="${1:-dist}"
URL="${VITE_PLUTO_URL:-${PLUTO_URL:-}}"
KEY="${VITE_PLUTO_ANON_KEY:-${PLUTO_ANON_KEY:-}}"

die()  { printf '\033[1;31m✗ %s\033[0m\n' "$*" >&2; exit 1; }
pass() { printf '\033[1;32m✓ %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*"; }

[[ -d "$DIST" ]] || die "dist dir not found: $DIST (run the frontend build first)"
[[ -n "$URL" ]]  || die "VITE_PLUTO_URL is required"
[[ -n "$KEY" ]]  || die "VITE_PLUTO_ANON_KEY is required"
[[ "$KEY" != "pk_anon_REPLACE_ME" ]] || die "VITE_PLUTO_ANON_KEY is still the placeholder pk_anon_REPLACE_ME"

cat > "$DIST/env.js" <<EOF
// generated by inject-pluto-env.sh at $(date -u +%FT%TZ)
window.__PLUTO_ENV__ = {
  url: "$URL",
  anonKey: "$KEY",
  VITE_PLUTO_URL: "$URL",
  VITE_PLUTO_ANON_KEY: "$KEY"
};
EOF
pass "wrote $DIST/env.js (url=$URL, key=${KEY:0:12}…)"

INDEX="$DIST/index.html"
SCRUBBED=0
while IFS= read -r -d '' html; do
  if grep -qiE "<link[^>]*(dns-prefetch|preconnect)[^>]*supabase\.(co|in)|<link[^>]*supabase\.(co|in)[^>]*(dns-prefetch|preconnect)" "$html"; then
    perl -0777 -i -pe '
      s#\s*<link\b(?=[^>]*\brel=["'"'](?:dns-prefetch|preconnect)["'"'])(?=[^>]*\bhref=["'"']https?://[a-z0-9-]+\.supabase\.(?:co|in)[^"'"'>]*["'"'])[^>]*>\s*\n?##gi;
      s#\s*<link\b(?=[^>]*\bhref=["'"']https?://[a-z0-9-]+\.supabase\.(?:co|in)[^"'"'>]*["'"'])(?=[^>]*\brel=["'"'](?:dns-prefetch|preconnect)["'"'])[^>]*>\s*\n?##gi;
    ' "$html"
    SCRUBBED=$((SCRUBBED + 1))
  fi
done < <(find "$DIST" -type f \( -name '*.html' -o -name '*.htm' \) -print0 2>/dev/null)
if [[ $SCRUBBED -gt 0 ]]; then
  warn "removed stale Supabase preconnect/dns-prefetch hints from $SCRUBBED HTML file(s)"
fi

if [[ -f "$INDEX" ]] && ! grep -q 'src="/env.js"' "$INDEX"; then
  # inject before first <script type="module"> or before </head>
  perl -0777 -i -pe '
    if ($_ =~ /<script\b[^>]*\btype=["'"'"']module["'"'"']/i) {
      s#(\s*<script\b[^>]*\btype=["'"'"']module["'"'"'])#\n    <script src="/env.js"></script>$1#i;
    } else {
      s#</head>#    <script src="/env.js"></script>\n  </head>#i;
    }
  ' "$INDEX"
  pass "injected <script src=\"/env.js\"> into $INDEX"
fi
