/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DashboardWorkspacesRouteImport } from './routes/dashboard.workspaces'
import { Route as DashboardVerifyRouteImport } from './routes/dashboard.verify'
import { Route as DashboardVectorRouteImport } from './routes/dashboard.vector'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as DashboardTokensRouteImport } from './routes/dashboard.tokens'
import { Route as DashboardStorageRouteImport } from './routes/dashboard.storage'
import { Route as DashboardSqlRouteImport } from './routes/dashboard.sql'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSdkDemoRouteImport } from './routes/dashboard.sdk-demo'
import { Route as DashboardScalingRouteImport } from './routes/dashboard.scaling'
import { Route as DashboardRealtimeRouteImport } from './routes/dashboard.realtime'
import { Route as DashboardRbacRouteImport } from './routes/dashboard.rbac'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardPlutoWebhooksRouteImport } from './routes/dashboard.pluto-webhooks'
import { Route as DashboardPlutoVaultRouteImport } from './routes/dashboard.pluto-vault'
import { Route as DashboardPlutoStudioRouteImport } from './routes/dashboard.pluto-studio'
import { Route as DashboardPlutoStoragePlusRouteImport } from './routes/dashboard.pluto-storage-plus'
import { Route as DashboardPlutoSearchRouteImport } from './routes/dashboard.pluto-search'
import { Route as DashboardPlutoSdkRouteImport } from './routes/dashboard.pluto-sdk'
import { Route as DashboardPlutoSchemaRouteImport } from './routes/dashboard.pluto-schema'
import { Route as DashboardPlutoReplicasRouteImport } from './routes/dashboard.pluto-replicas'
import { Route as DashboardPlutoRealtimeRouteImport } from './routes/dashboard.pluto-realtime'
import { Route as DashboardPlutoQueuesRouteImport } from './routes/dashboard.pluto-queues'
import { Route as DashboardPlutoOrgsRouteImport } from './routes/dashboard.pluto-orgs'
import { Route as DashboardPlutoMigrationsRouteImport } from './routes/dashboard.pluto-migrations'
import { Route as DashboardPlutoMarketplaceRouteImport } from './routes/dashboard.pluto-marketplace'
import { Route as DashboardPlutoGraphqlRouteImport } from './routes/dashboard.pluto-graphql'
import { Route as DashboardPlutoFunctionsPlusRouteImport } from './routes/dashboard.pluto-functions-plus'
import { Route as DashboardPlutoFunctionsRouteImport } from './routes/dashboard.pluto-functions'
import { Route as DashboardPlutoComplianceRouteImport } from './routes/dashboard.pluto-compliance'
import { Route as DashboardPlutoBranchesRouteImport } from './routes/dashboard.pluto-branches'
import { Route as DashboardPlutoBillingRouteImport } from './routes/dashboard.pluto-billing'
import { Route as DashboardPlutoBackupsRouteImport } from './routes/dashboard.pluto-backups'
import { Route as DashboardPlutoAuthAdvancedRouteImport } from './routes/dashboard.pluto-auth-advanced'
import { Route as DashboardPlutoAuditRouteImport } from './routes/dashboard.pluto-audit'
import { Route as DashboardPlutoAiRouteImport } from './routes/dashboard.pluto-ai'
import { Route as DashboardPlutoAdminRouteImport } from './routes/dashboard.pluto-admin'
import { Route as DashboardObservabilityRouteImport } from './routes/dashboard.observability'
import { Route as DashboardMigrationsRouteImport } from './routes/dashboard.migrations'
import { Route as DashboardMfaRouteImport } from './routes/dashboard.mfa'
import { Route as DashboardLogsExplorerRouteImport } from './routes/dashboard.logs-explorer'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard.integrations'
import { Route as DashboardGraphqlRouteImport } from './routes/dashboard.graphql'
import { Route as DashboardFunctionsRouteImport } from './routes/dashboard.functions'
import { Route as DashboardEnterpriseRouteImport } from './routes/dashboard.enterprise'
import { Route as DashboardDevexRouteImport } from './routes/dashboard.devex'
import { Route as DashboardDatabaseRouteImport } from './routes/dashboard.database'
import { Route as DashboardCorsRouteImport } from './routes/dashboard.cors'
import { Route as DashboardBranchingRouteImport } from './routes/dashboard.branching'
import { Route as DashboardBackupsRouteImport } from './routes/dashboard.backups'
import { Route as DashboardAuditLogRouteImport } from './routes/dashboard.audit-log'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardApiRouteImport } from './routes/dashboard.api'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthPhoneRouteImport } from './routes/auth.phone'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth.confirm-email'
import { Route as ApiPlutoStatusRouteImport } from './routes/api/pluto.status'
import { Route as ApiPlutoMonitorRouteImport } from './routes/api/pluto.monitor'
import { Route as ApiPlutoSplatRouteImport } from './routes/api/pluto.$'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspacesRoute = DashboardWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerifyRoute = DashboardVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVectorRoute = DashboardVectorRouteImport.update({
  id: '/vector',
  path: '/vector',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTokensRoute = DashboardTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSqlRoute = DashboardSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSdkDemoRoute = DashboardSdkDemoRouteImport.update({
  id: '/sdk-demo',
  path: '/sdk-demo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScalingRoute = DashboardScalingRouteImport.update({
  id: '/scaling',
  path: '/scaling',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRealtimeRoute = DashboardRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRbacRoute = DashboardRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoWebhooksRoute = DashboardPlutoWebhooksRouteImport.update({
  id: '/pluto-webhooks',
  path: '/pluto-webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoVaultRoute = DashboardPlutoVaultRouteImport.update({
  id: '/pluto-vault',
  path: '/pluto-vault',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoStudioRoute = DashboardPlutoStudioRouteImport.update({
  id: '/pluto-studio',
  path: '/pluto-studio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoStoragePlusRoute =
  DashboardPlutoStoragePlusRouteImport.update({
    id: '/pluto-storage-plus',
    path: '/pluto-storage-plus',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlutoSearchRoute = DashboardPlutoSearchRouteImport.update({
  id: '/pluto-search',
  path: '/pluto-search',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoSdkRoute = DashboardPlutoSdkRouteImport.update({
  id: '/pluto-sdk',
  path: '/pluto-sdk',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoSchemaRoute = DashboardPlutoSchemaRouteImport.update({
  id: '/pluto-schema',
  path: '/pluto-schema',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoReplicasRoute = DashboardPlutoReplicasRouteImport.update({
  id: '/pluto-replicas',
  path: '/pluto-replicas',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoRealtimeRoute = DashboardPlutoRealtimeRouteImport.update({
  id: '/pluto-realtime',
  path: '/pluto-realtime',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoQueuesRoute = DashboardPlutoQueuesRouteImport.update({
  id: '/pluto-queues',
  path: '/pluto-queues',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoOrgsRoute = DashboardPlutoOrgsRouteImport.update({
  id: '/pluto-orgs',
  path: '/pluto-orgs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoMigrationsRoute =
  DashboardPlutoMigrationsRouteImport.update({
    id: '/pluto-migrations',
    path: '/pluto-migrations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlutoMarketplaceRoute =
  DashboardPlutoMarketplaceRouteImport.update({
    id: '/pluto-marketplace',
    path: '/pluto-marketplace',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlutoGraphqlRoute = DashboardPlutoGraphqlRouteImport.update({
  id: '/pluto-graphql',
  path: '/pluto-graphql',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoFunctionsPlusRoute =
  DashboardPlutoFunctionsPlusRouteImport.update({
    id: '/pluto-functions-plus',
    path: '/pluto-functions-plus',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlutoFunctionsRoute = DashboardPlutoFunctionsRouteImport.update({
  id: '/pluto-functions',
  path: '/pluto-functions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoComplianceRoute =
  DashboardPlutoComplianceRouteImport.update({
    id: '/pluto-compliance',
    path: '/pluto-compliance',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlutoBranchesRoute = DashboardPlutoBranchesRouteImport.update({
  id: '/pluto-branches',
  path: '/pluto-branches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoBillingRoute = DashboardPlutoBillingRouteImport.update({
  id: '/pluto-billing',
  path: '/pluto-billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoBackupsRoute = DashboardPlutoBackupsRouteImport.update({
  id: '/pluto-backups',
  path: '/pluto-backups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoAuthAdvancedRoute =
  DashboardPlutoAuthAdvancedRouteImport.update({
    id: '/pluto-auth-advanced',
    path: '/pluto-auth-advanced',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPlutoAuditRoute = DashboardPlutoAuditRouteImport.update({
  id: '/pluto-audit',
  path: '/pluto-audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoAiRoute = DashboardPlutoAiRouteImport.update({
  id: '/pluto-ai',
  path: '/pluto-ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlutoAdminRoute = DashboardPlutoAdminRouteImport.update({
  id: '/pluto-admin',
  path: '/pluto-admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObservabilityRoute = DashboardObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMigrationsRoute = DashboardMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMfaRoute = DashboardMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsExplorerRoute = DashboardLogsExplorerRouteImport.update({
  id: '/logs-explorer',
  path: '/logs-explorer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGraphqlRoute = DashboardGraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFunctionsRoute = DashboardFunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnterpriseRoute = DashboardEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevexRoute = DashboardDevexRouteImport.update({
  id: '/devex',
  path: '/devex',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabaseRoute = DashboardDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCorsRoute = DashboardCorsRouteImport.update({
  id: '/cors',
  path: '/cors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchingRoute = DashboardBranchingRouteImport.update({
  id: '/branching',
  path: '/branching',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackupsRoute = DashboardBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogRoute = DashboardAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiRoute = DashboardApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPhoneRoute = AuthPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPlutoStatusRoute = ApiPlutoStatusRouteImport.update({
  id: '/api/pluto/status',
  path: '/api/pluto/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlutoMonitorRoute = ApiPlutoMonitorRouteImport.update({
  id: '/api/pluto/monitor',
  path: '/api/pluto/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlutoSplatRoute = ApiPlutoSplatRouteImport.update({
  id: '/api/pluto/$',
  path: '/api/pluto/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/cors': typeof DashboardCorsRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/functions': typeof DashboardFunctionsRoute
  '/dashboard/graphql': typeof DashboardGraphqlRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/logs-explorer': typeof DashboardLogsExplorerRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/pluto-admin': typeof DashboardPlutoAdminRoute
  '/dashboard/pluto-ai': typeof DashboardPlutoAiRoute
  '/dashboard/pluto-audit': typeof DashboardPlutoAuditRoute
  '/dashboard/pluto-auth-advanced': typeof DashboardPlutoAuthAdvancedRoute
  '/dashboard/pluto-backups': typeof DashboardPlutoBackupsRoute
  '/dashboard/pluto-billing': typeof DashboardPlutoBillingRoute
  '/dashboard/pluto-branches': typeof DashboardPlutoBranchesRoute
  '/dashboard/pluto-compliance': typeof DashboardPlutoComplianceRoute
  '/dashboard/pluto-functions': typeof DashboardPlutoFunctionsRoute
  '/dashboard/pluto-functions-plus': typeof DashboardPlutoFunctionsPlusRoute
  '/dashboard/pluto-graphql': typeof DashboardPlutoGraphqlRoute
  '/dashboard/pluto-marketplace': typeof DashboardPlutoMarketplaceRoute
  '/dashboard/pluto-migrations': typeof DashboardPlutoMigrationsRoute
  '/dashboard/pluto-orgs': typeof DashboardPlutoOrgsRoute
  '/dashboard/pluto-queues': typeof DashboardPlutoQueuesRoute
  '/dashboard/pluto-realtime': typeof DashboardPlutoRealtimeRoute
  '/dashboard/pluto-replicas': typeof DashboardPlutoReplicasRoute
  '/dashboard/pluto-schema': typeof DashboardPlutoSchemaRoute
  '/dashboard/pluto-sdk': typeof DashboardPlutoSdkRoute
  '/dashboard/pluto-search': typeof DashboardPlutoSearchRoute
  '/dashboard/pluto-storage-plus': typeof DashboardPlutoStoragePlusRoute
  '/dashboard/pluto-studio': typeof DashboardPlutoStudioRoute
  '/dashboard/pluto-vault': typeof DashboardPlutoVaultRoute
  '/dashboard/pluto-webhooks': typeof DashboardPlutoWebhooksRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac': typeof DashboardRbacRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/sdk-demo': typeof DashboardSdkDemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vector': typeof DashboardVectorRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/docs/api': typeof DocsApiRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/pluto/$': typeof ApiPlutoSplatRoute
  '/api/pluto/monitor': typeof ApiPlutoMonitorRoute
  '/api/pluto/status': typeof ApiPlutoStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/cors': typeof DashboardCorsRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/functions': typeof DashboardFunctionsRoute
  '/dashboard/graphql': typeof DashboardGraphqlRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/logs-explorer': typeof DashboardLogsExplorerRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/pluto-admin': typeof DashboardPlutoAdminRoute
  '/dashboard/pluto-ai': typeof DashboardPlutoAiRoute
  '/dashboard/pluto-audit': typeof DashboardPlutoAuditRoute
  '/dashboard/pluto-auth-advanced': typeof DashboardPlutoAuthAdvancedRoute
  '/dashboard/pluto-backups': typeof DashboardPlutoBackupsRoute
  '/dashboard/pluto-billing': typeof DashboardPlutoBillingRoute
  '/dashboard/pluto-branches': typeof DashboardPlutoBranchesRoute
  '/dashboard/pluto-compliance': typeof DashboardPlutoComplianceRoute
  '/dashboard/pluto-functions': typeof DashboardPlutoFunctionsRoute
  '/dashboard/pluto-functions-plus': typeof DashboardPlutoFunctionsPlusRoute
  '/dashboard/pluto-graphql': typeof DashboardPlutoGraphqlRoute
  '/dashboard/pluto-marketplace': typeof DashboardPlutoMarketplaceRoute
  '/dashboard/pluto-migrations': typeof DashboardPlutoMigrationsRoute
  '/dashboard/pluto-orgs': typeof DashboardPlutoOrgsRoute
  '/dashboard/pluto-queues': typeof DashboardPlutoQueuesRoute
  '/dashboard/pluto-realtime': typeof DashboardPlutoRealtimeRoute
  '/dashboard/pluto-replicas': typeof DashboardPlutoReplicasRoute
  '/dashboard/pluto-schema': typeof DashboardPlutoSchemaRoute
  '/dashboard/pluto-sdk': typeof DashboardPlutoSdkRoute
  '/dashboard/pluto-search': typeof DashboardPlutoSearchRoute
  '/dashboard/pluto-storage-plus': typeof DashboardPlutoStoragePlusRoute
  '/dashboard/pluto-studio': typeof DashboardPlutoStudioRoute
  '/dashboard/pluto-vault': typeof DashboardPlutoVaultRoute
  '/dashboard/pluto-webhooks': typeof DashboardPlutoWebhooksRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac': typeof DashboardRbacRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/sdk-demo': typeof DashboardSdkDemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vector': typeof DashboardVectorRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/docs/api': typeof DocsApiRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/pluto/$': typeof ApiPlutoSplatRoute
  '/api/pluto/monitor': typeof ApiPlutoMonitorRoute
  '/api/pluto/status': typeof ApiPlutoStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/cors': typeof DashboardCorsRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/functions': typeof DashboardFunctionsRoute
  '/dashboard/graphql': typeof DashboardGraphqlRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/logs-explorer': typeof DashboardLogsExplorerRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/pluto-admin': typeof DashboardPlutoAdminRoute
  '/dashboard/pluto-ai': typeof DashboardPlutoAiRoute
  '/dashboard/pluto-audit': typeof DashboardPlutoAuditRoute
  '/dashboard/pluto-auth-advanced': typeof DashboardPlutoAuthAdvancedRoute
  '/dashboard/pluto-backups': typeof DashboardPlutoBackupsRoute
  '/dashboard/pluto-billing': typeof DashboardPlutoBillingRoute
  '/dashboard/pluto-branches': typeof DashboardPlutoBranchesRoute
  '/dashboard/pluto-compliance': typeof DashboardPlutoComplianceRoute
  '/dashboard/pluto-functions': typeof DashboardPlutoFunctionsRoute
  '/dashboard/pluto-functions-plus': typeof DashboardPlutoFunctionsPlusRoute
  '/dashboard/pluto-graphql': typeof DashboardPlutoGraphqlRoute
  '/dashboard/pluto-marketplace': typeof DashboardPlutoMarketplaceRoute
  '/dashboard/pluto-migrations': typeof DashboardPlutoMigrationsRoute
  '/dashboard/pluto-orgs': typeof DashboardPlutoOrgsRoute
  '/dashboard/pluto-queues': typeof DashboardPlutoQueuesRoute
  '/dashboard/pluto-realtime': typeof DashboardPlutoRealtimeRoute
  '/dashboard/pluto-replicas': typeof DashboardPlutoReplicasRoute
  '/dashboard/pluto-schema': typeof DashboardPlutoSchemaRoute
  '/dashboard/pluto-sdk': typeof DashboardPlutoSdkRoute
  '/dashboard/pluto-search': typeof DashboardPlutoSearchRoute
  '/dashboard/pluto-storage-plus': typeof DashboardPlutoStoragePlusRoute
  '/dashboard/pluto-studio': typeof DashboardPlutoStudioRoute
  '/dashboard/pluto-vault': typeof DashboardPlutoVaultRoute
  '/dashboard/pluto-webhooks': typeof DashboardPlutoWebhooksRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac': typeof DashboardRbacRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/sdk-demo': typeof DashboardSdkDemoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vector': typeof DashboardVectorRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/docs/api': typeof DocsApiRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/pluto/$': typeof ApiPlutoSplatRoute
  '/api/pluto/monitor': typeof ApiPlutoMonitorRoute
  '/api/pluto/status': typeof ApiPlutoStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sitemap.xml'
    | '/status'
    | '/auth/confirm-email'
    | '/auth/forgot'
    | '/auth/phone'
    | '/auth/reset-password'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/audit-log'
    | '/dashboard/backups'
    | '/dashboard/branching'
    | '/dashboard/cors'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/functions'
    | '/dashboard/graphql'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/logs-explorer'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/pluto-admin'
    | '/dashboard/pluto-ai'
    | '/dashboard/pluto-audit'
    | '/dashboard/pluto-auth-advanced'
    | '/dashboard/pluto-backups'
    | '/dashboard/pluto-billing'
    | '/dashboard/pluto-branches'
    | '/dashboard/pluto-compliance'
    | '/dashboard/pluto-functions'
    | '/dashboard/pluto-functions-plus'
    | '/dashboard/pluto-graphql'
    | '/dashboard/pluto-marketplace'
    | '/dashboard/pluto-migrations'
    | '/dashboard/pluto-orgs'
    | '/dashboard/pluto-queues'
    | '/dashboard/pluto-realtime'
    | '/dashboard/pluto-replicas'
    | '/dashboard/pluto-schema'
    | '/dashboard/pluto-sdk'
    | '/dashboard/pluto-search'
    | '/dashboard/pluto-storage-plus'
    | '/dashboard/pluto-studio'
    | '/dashboard/pluto-vault'
    | '/dashboard/pluto-webhooks'
    | '/dashboard/projects'
    | '/dashboard/rbac'
    | '/dashboard/realtime'
    | '/dashboard/scaling'
    | '/dashboard/sdk-demo'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/tokens'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard/vector'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/docs/api'
    | '/dashboard/'
    | '/api/pluto/$'
    | '/api/pluto/monitor'
    | '/api/pluto/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/status'
    | '/auth/confirm-email'
    | '/auth/forgot'
    | '/auth/phone'
    | '/auth/reset-password'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/audit-log'
    | '/dashboard/backups'
    | '/dashboard/branching'
    | '/dashboard/cors'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/functions'
    | '/dashboard/graphql'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/logs-explorer'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/pluto-admin'
    | '/dashboard/pluto-ai'
    | '/dashboard/pluto-audit'
    | '/dashboard/pluto-auth-advanced'
    | '/dashboard/pluto-backups'
    | '/dashboard/pluto-billing'
    | '/dashboard/pluto-branches'
    | '/dashboard/pluto-compliance'
    | '/dashboard/pluto-functions'
    | '/dashboard/pluto-functions-plus'
    | '/dashboard/pluto-graphql'
    | '/dashboard/pluto-marketplace'
    | '/dashboard/pluto-migrations'
    | '/dashboard/pluto-orgs'
    | '/dashboard/pluto-queues'
    | '/dashboard/pluto-realtime'
    | '/dashboard/pluto-replicas'
    | '/dashboard/pluto-schema'
    | '/dashboard/pluto-sdk'
    | '/dashboard/pluto-search'
    | '/dashboard/pluto-storage-plus'
    | '/dashboard/pluto-studio'
    | '/dashboard/pluto-vault'
    | '/dashboard/pluto-webhooks'
    | '/dashboard/projects'
    | '/dashboard/rbac'
    | '/dashboard/realtime'
    | '/dashboard/scaling'
    | '/dashboard/sdk-demo'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/tokens'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard/vector'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/docs/api'
    | '/dashboard'
    | '/api/pluto/$'
    | '/api/pluto/monitor'
    | '/api/pluto/status'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/sitemap.xml'
    | '/status'
    | '/auth/confirm-email'
    | '/auth/forgot'
    | '/auth/phone'
    | '/auth/reset-password'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/audit-log'
    | '/dashboard/backups'
    | '/dashboard/branching'
    | '/dashboard/cors'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/functions'
    | '/dashboard/graphql'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/logs-explorer'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/pluto-admin'
    | '/dashboard/pluto-ai'
    | '/dashboard/pluto-audit'
    | '/dashboard/pluto-auth-advanced'
    | '/dashboard/pluto-backups'
    | '/dashboard/pluto-billing'
    | '/dashboard/pluto-branches'
    | '/dashboard/pluto-compliance'
    | '/dashboard/pluto-functions'
    | '/dashboard/pluto-functions-plus'
    | '/dashboard/pluto-graphql'
    | '/dashboard/pluto-marketplace'
    | '/dashboard/pluto-migrations'
    | '/dashboard/pluto-orgs'
    | '/dashboard/pluto-queues'
    | '/dashboard/pluto-realtime'
    | '/dashboard/pluto-replicas'
    | '/dashboard/pluto-schema'
    | '/dashboard/pluto-sdk'
    | '/dashboard/pluto-search'
    | '/dashboard/pluto-storage-plus'
    | '/dashboard/pluto-studio'
    | '/dashboard/pluto-vault'
    | '/dashboard/pluto-webhooks'
    | '/dashboard/projects'
    | '/dashboard/rbac'
    | '/dashboard/realtime'
    | '/dashboard/scaling'
    | '/dashboard/sdk-demo'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/tokens'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard/vector'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/docs/api'
    | '/dashboard/'
    | '/api/pluto/$'
    | '/api/pluto/monitor'
    | '/api/pluto/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  DocsApiRoute: typeof DocsApiRoute
  ApiPlutoSplatRoute: typeof ApiPlutoSplatRoute
  ApiPlutoMonitorRoute: typeof ApiPlutoMonitorRoute
  ApiPlutoStatusRoute: typeof ApiPlutoStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspaces': {
      id: '/dashboard/workspaces'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces'
      preLoaderRoute: typeof DashboardWorkspacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verify': {
      id: '/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof DashboardVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vector': {
      id: '/dashboard/vector'
      path: '/vector'
      fullPath: '/dashboard/vector'
      preLoaderRoute: typeof DashboardVectorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tokens': {
      id: '/dashboard/tokens'
      path: '/tokens'
      fullPath: '/dashboard/tokens'
      preLoaderRoute: typeof DashboardTokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sql': {
      id: '/dashboard/sql'
      path: '/sql'
      fullPath: '/dashboard/sql'
      preLoaderRoute: typeof DashboardSqlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sdk-demo': {
      id: '/dashboard/sdk-demo'
      path: '/sdk-demo'
      fullPath: '/dashboard/sdk-demo'
      preLoaderRoute: typeof DashboardSdkDemoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scaling': {
      id: '/dashboard/scaling'
      path: '/scaling'
      fullPath: '/dashboard/scaling'
      preLoaderRoute: typeof DashboardScalingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/realtime': {
      id: '/dashboard/realtime'
      path: '/realtime'
      fullPath: '/dashboard/realtime'
      preLoaderRoute: typeof DashboardRealtimeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rbac': {
      id: '/dashboard/rbac'
      path: '/rbac'
      fullPath: '/dashboard/rbac'
      preLoaderRoute: typeof DashboardRbacRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-webhooks': {
      id: '/dashboard/pluto-webhooks'
      path: '/pluto-webhooks'
      fullPath: '/dashboard/pluto-webhooks'
      preLoaderRoute: typeof DashboardPlutoWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-vault': {
      id: '/dashboard/pluto-vault'
      path: '/pluto-vault'
      fullPath: '/dashboard/pluto-vault'
      preLoaderRoute: typeof DashboardPlutoVaultRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-studio': {
      id: '/dashboard/pluto-studio'
      path: '/pluto-studio'
      fullPath: '/dashboard/pluto-studio'
      preLoaderRoute: typeof DashboardPlutoStudioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-storage-plus': {
      id: '/dashboard/pluto-storage-plus'
      path: '/pluto-storage-plus'
      fullPath: '/dashboard/pluto-storage-plus'
      preLoaderRoute: typeof DashboardPlutoStoragePlusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-search': {
      id: '/dashboard/pluto-search'
      path: '/pluto-search'
      fullPath: '/dashboard/pluto-search'
      preLoaderRoute: typeof DashboardPlutoSearchRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-sdk': {
      id: '/dashboard/pluto-sdk'
      path: '/pluto-sdk'
      fullPath: '/dashboard/pluto-sdk'
      preLoaderRoute: typeof DashboardPlutoSdkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-schema': {
      id: '/dashboard/pluto-schema'
      path: '/pluto-schema'
      fullPath: '/dashboard/pluto-schema'
      preLoaderRoute: typeof DashboardPlutoSchemaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-replicas': {
      id: '/dashboard/pluto-replicas'
      path: '/pluto-replicas'
      fullPath: '/dashboard/pluto-replicas'
      preLoaderRoute: typeof DashboardPlutoReplicasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-realtime': {
      id: '/dashboard/pluto-realtime'
      path: '/pluto-realtime'
      fullPath: '/dashboard/pluto-realtime'
      preLoaderRoute: typeof DashboardPlutoRealtimeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-queues': {
      id: '/dashboard/pluto-queues'
      path: '/pluto-queues'
      fullPath: '/dashboard/pluto-queues'
      preLoaderRoute: typeof DashboardPlutoQueuesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-orgs': {
      id: '/dashboard/pluto-orgs'
      path: '/pluto-orgs'
      fullPath: '/dashboard/pluto-orgs'
      preLoaderRoute: typeof DashboardPlutoOrgsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-migrations': {
      id: '/dashboard/pluto-migrations'
      path: '/pluto-migrations'
      fullPath: '/dashboard/pluto-migrations'
      preLoaderRoute: typeof DashboardPlutoMigrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-marketplace': {
      id: '/dashboard/pluto-marketplace'
      path: '/pluto-marketplace'
      fullPath: '/dashboard/pluto-marketplace'
      preLoaderRoute: typeof DashboardPlutoMarketplaceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-graphql': {
      id: '/dashboard/pluto-graphql'
      path: '/pluto-graphql'
      fullPath: '/dashboard/pluto-graphql'
      preLoaderRoute: typeof DashboardPlutoGraphqlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-functions-plus': {
      id: '/dashboard/pluto-functions-plus'
      path: '/pluto-functions-plus'
      fullPath: '/dashboard/pluto-functions-plus'
      preLoaderRoute: typeof DashboardPlutoFunctionsPlusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-functions': {
      id: '/dashboard/pluto-functions'
      path: '/pluto-functions'
      fullPath: '/dashboard/pluto-functions'
      preLoaderRoute: typeof DashboardPlutoFunctionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-compliance': {
      id: '/dashboard/pluto-compliance'
      path: '/pluto-compliance'
      fullPath: '/dashboard/pluto-compliance'
      preLoaderRoute: typeof DashboardPlutoComplianceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-branches': {
      id: '/dashboard/pluto-branches'
      path: '/pluto-branches'
      fullPath: '/dashboard/pluto-branches'
      preLoaderRoute: typeof DashboardPlutoBranchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-billing': {
      id: '/dashboard/pluto-billing'
      path: '/pluto-billing'
      fullPath: '/dashboard/pluto-billing'
      preLoaderRoute: typeof DashboardPlutoBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-backups': {
      id: '/dashboard/pluto-backups'
      path: '/pluto-backups'
      fullPath: '/dashboard/pluto-backups'
      preLoaderRoute: typeof DashboardPlutoBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-auth-advanced': {
      id: '/dashboard/pluto-auth-advanced'
      path: '/pluto-auth-advanced'
      fullPath: '/dashboard/pluto-auth-advanced'
      preLoaderRoute: typeof DashboardPlutoAuthAdvancedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-audit': {
      id: '/dashboard/pluto-audit'
      path: '/pluto-audit'
      fullPath: '/dashboard/pluto-audit'
      preLoaderRoute: typeof DashboardPlutoAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-ai': {
      id: '/dashboard/pluto-ai'
      path: '/pluto-ai'
      fullPath: '/dashboard/pluto-ai'
      preLoaderRoute: typeof DashboardPlutoAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pluto-admin': {
      id: '/dashboard/pluto-admin'
      path: '/pluto-admin'
      fullPath: '/dashboard/pluto-admin'
      preLoaderRoute: typeof DashboardPlutoAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/observability': {
      id: '/dashboard/observability'
      path: '/observability'
      fullPath: '/dashboard/observability'
      preLoaderRoute: typeof DashboardObservabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/migrations': {
      id: '/dashboard/migrations'
      path: '/migrations'
      fullPath: '/dashboard/migrations'
      preLoaderRoute: typeof DashboardMigrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mfa': {
      id: '/dashboard/mfa'
      path: '/mfa'
      fullPath: '/dashboard/mfa'
      preLoaderRoute: typeof DashboardMfaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs-explorer': {
      id: '/dashboard/logs-explorer'
      path: '/logs-explorer'
      fullPath: '/dashboard/logs-explorer'
      preLoaderRoute: typeof DashboardLogsExplorerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/graphql': {
      id: '/dashboard/graphql'
      path: '/graphql'
      fullPath: '/dashboard/graphql'
      preLoaderRoute: typeof DashboardGraphqlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/functions': {
      id: '/dashboard/functions'
      path: '/functions'
      fullPath: '/dashboard/functions'
      preLoaderRoute: typeof DashboardFunctionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enterprise': {
      id: '/dashboard/enterprise'
      path: '/enterprise'
      fullPath: '/dashboard/enterprise'
      preLoaderRoute: typeof DashboardEnterpriseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devex': {
      id: '/dashboard/devex'
      path: '/devex'
      fullPath: '/dashboard/devex'
      preLoaderRoute: typeof DashboardDevexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/database': {
      id: '/dashboard/database'
      path: '/database'
      fullPath: '/dashboard/database'
      preLoaderRoute: typeof DashboardDatabaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/cors': {
      id: '/dashboard/cors'
      path: '/cors'
      fullPath: '/dashboard/cors'
      preLoaderRoute: typeof DashboardCorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branching': {
      id: '/dashboard/branching'
      path: '/branching'
      fullPath: '/dashboard/branching'
      preLoaderRoute: typeof DashboardBranchingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/backups': {
      id: '/dashboard/backups'
      path: '/backups'
      fullPath: '/dashboard/backups'
      preLoaderRoute: typeof DashboardBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-log': {
      id: '/dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/audit-log'
      preLoaderRoute: typeof DashboardAuditLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api': {
      id: '/dashboard/api'
      path: '/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof DashboardApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/phone': {
      id: '/auth/phone'
      path: '/phone'
      fullPath: '/auth/phone'
      preLoaderRoute: typeof AuthPhoneRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/pluto/status': {
      id: '/api/pluto/status'
      path: '/api/pluto/status'
      fullPath: '/api/pluto/status'
      preLoaderRoute: typeof ApiPlutoStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pluto/monitor': {
      id: '/api/pluto/monitor'
      path: '/api/pluto/monitor'
      fullPath: '/api/pluto/monitor'
      preLoaderRoute: typeof ApiPlutoMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pluto/$': {
      id: '/api/pluto/$'
      path: '/api/pluto/$'
      fullPath: '/api/pluto/$'
      preLoaderRoute: typeof ApiPlutoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthPhoneRoute: typeof AuthPhoneRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthPhoneRoute: AuthPhoneRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardApiRoute: typeof DashboardApiRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardAuditLogRoute: typeof DashboardAuditLogRoute
  DashboardBackupsRoute: typeof DashboardBackupsRoute
  DashboardBranchingRoute: typeof DashboardBranchingRoute
  DashboardCorsRoute: typeof DashboardCorsRoute
  DashboardDatabaseRoute: typeof DashboardDatabaseRoute
  DashboardDevexRoute: typeof DashboardDevexRoute
  DashboardEnterpriseRoute: typeof DashboardEnterpriseRoute
  DashboardFunctionsRoute: typeof DashboardFunctionsRoute
  DashboardGraphqlRoute: typeof DashboardGraphqlRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardLogsExplorerRoute: typeof DashboardLogsExplorerRoute
  DashboardMfaRoute: typeof DashboardMfaRoute
  DashboardMigrationsRoute: typeof DashboardMigrationsRoute
  DashboardObservabilityRoute: typeof DashboardObservabilityRoute
  DashboardPlutoAdminRoute: typeof DashboardPlutoAdminRoute
  DashboardPlutoAiRoute: typeof DashboardPlutoAiRoute
  DashboardPlutoAuditRoute: typeof DashboardPlutoAuditRoute
  DashboardPlutoAuthAdvancedRoute: typeof DashboardPlutoAuthAdvancedRoute
  DashboardPlutoBackupsRoute: typeof DashboardPlutoBackupsRoute
  DashboardPlutoBillingRoute: typeof DashboardPlutoBillingRoute
  DashboardPlutoBranchesRoute: typeof DashboardPlutoBranchesRoute
  DashboardPlutoComplianceRoute: typeof DashboardPlutoComplianceRoute
  DashboardPlutoFunctionsRoute: typeof DashboardPlutoFunctionsRoute
  DashboardPlutoFunctionsPlusRoute: typeof DashboardPlutoFunctionsPlusRoute
  DashboardPlutoGraphqlRoute: typeof DashboardPlutoGraphqlRoute
  DashboardPlutoMarketplaceRoute: typeof DashboardPlutoMarketplaceRoute
  DashboardPlutoMigrationsRoute: typeof DashboardPlutoMigrationsRoute
  DashboardPlutoOrgsRoute: typeof DashboardPlutoOrgsRoute
  DashboardPlutoQueuesRoute: typeof DashboardPlutoQueuesRoute
  DashboardPlutoRealtimeRoute: typeof DashboardPlutoRealtimeRoute
  DashboardPlutoReplicasRoute: typeof DashboardPlutoReplicasRoute
  DashboardPlutoSchemaRoute: typeof DashboardPlutoSchemaRoute
  DashboardPlutoSdkRoute: typeof DashboardPlutoSdkRoute
  DashboardPlutoSearchRoute: typeof DashboardPlutoSearchRoute
  DashboardPlutoStoragePlusRoute: typeof DashboardPlutoStoragePlusRoute
  DashboardPlutoStudioRoute: typeof DashboardPlutoStudioRoute
  DashboardPlutoVaultRoute: typeof DashboardPlutoVaultRoute
  DashboardPlutoWebhooksRoute: typeof DashboardPlutoWebhooksRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardRbacRoute: typeof DashboardRbacRoute
  DashboardRealtimeRoute: typeof DashboardRealtimeRoute
  DashboardScalingRoute: typeof DashboardScalingRoute
  DashboardSdkDemoRoute: typeof DashboardSdkDemoRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSqlRoute: typeof DashboardSqlRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardTokensRoute: typeof DashboardTokensRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardVectorRoute: typeof DashboardVectorRoute
  DashboardVerifyRoute: typeof DashboardVerifyRoute
  DashboardWorkspacesRoute: typeof DashboardWorkspacesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardApiRoute: DashboardApiRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardAuditLogRoute: DashboardAuditLogRoute,
  DashboardBackupsRoute: DashboardBackupsRoute,
  DashboardBranchingRoute: DashboardBranchingRoute,
  DashboardCorsRoute: DashboardCorsRoute,
  DashboardDatabaseRoute: DashboardDatabaseRoute,
  DashboardDevexRoute: DashboardDevexRoute,
  DashboardEnterpriseRoute: DashboardEnterpriseRoute,
  DashboardFunctionsRoute: DashboardFunctionsRoute,
  DashboardGraphqlRoute: DashboardGraphqlRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardLogsExplorerRoute: DashboardLogsExplorerRoute,
  DashboardMfaRoute: DashboardMfaRoute,
  DashboardMigrationsRoute: DashboardMigrationsRoute,
  DashboardObservabilityRoute: DashboardObservabilityRoute,
  DashboardPlutoAdminRoute: DashboardPlutoAdminRoute,
  DashboardPlutoAiRoute: DashboardPlutoAiRoute,
  DashboardPlutoAuditRoute: DashboardPlutoAuditRoute,
  DashboardPlutoAuthAdvancedRoute: DashboardPlutoAuthAdvancedRoute,
  DashboardPlutoBackupsRoute: DashboardPlutoBackupsRoute,
  DashboardPlutoBillingRoute: DashboardPlutoBillingRoute,
  DashboardPlutoBranchesRoute: DashboardPlutoBranchesRoute,
  DashboardPlutoComplianceRoute: DashboardPlutoComplianceRoute,
  DashboardPlutoFunctionsRoute: DashboardPlutoFunctionsRoute,
  DashboardPlutoFunctionsPlusRoute: DashboardPlutoFunctionsPlusRoute,
  DashboardPlutoGraphqlRoute: DashboardPlutoGraphqlRoute,
  DashboardPlutoMarketplaceRoute: DashboardPlutoMarketplaceRoute,
  DashboardPlutoMigrationsRoute: DashboardPlutoMigrationsRoute,
  DashboardPlutoOrgsRoute: DashboardPlutoOrgsRoute,
  DashboardPlutoQueuesRoute: DashboardPlutoQueuesRoute,
  DashboardPlutoRealtimeRoute: DashboardPlutoRealtimeRoute,
  DashboardPlutoReplicasRoute: DashboardPlutoReplicasRoute,
  DashboardPlutoSchemaRoute: DashboardPlutoSchemaRoute,
  DashboardPlutoSdkRoute: DashboardPlutoSdkRoute,
  DashboardPlutoSearchRoute: DashboardPlutoSearchRoute,
  DashboardPlutoStoragePlusRoute: DashboardPlutoStoragePlusRoute,
  DashboardPlutoStudioRoute: DashboardPlutoStudioRoute,
  DashboardPlutoVaultRoute: DashboardPlutoVaultRoute,
  DashboardPlutoWebhooksRoute: DashboardPlutoWebhooksRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardRbacRoute: DashboardRbacRoute,
  DashboardRealtimeRoute: DashboardRealtimeRoute,
  DashboardScalingRoute: DashboardScalingRoute,
  DashboardSdkDemoRoute: DashboardSdkDemoRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSqlRoute: DashboardSqlRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardTokensRoute: DashboardTokensRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardVectorRoute: DashboardVectorRoute,
  DashboardVerifyRoute: DashboardVerifyRoute,
  DashboardWorkspacesRoute: DashboardWorkspacesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  DocsApiRoute: DocsApiRoute,
  ApiPlutoSplatRoute: ApiPlutoSplatRoute,
  ApiPlutoMonitorRoute: ApiPlutoMonitorRoute,
  ApiPlutoStatusRoute: ApiPlutoStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
