/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DashboardWorkspacesRouteImport } from './routes/dashboard.workspaces'
import { Route as DashboardVerifyRouteImport } from './routes/dashboard.verify'
import { Route as DashboardVectorRouteImport } from './routes/dashboard.vector'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardUsageRouteImport } from './routes/dashboard.usage'
import { Route as DashboardTokensRouteImport } from './routes/dashboard.tokens'
import { Route as DashboardStorageRouteImport } from './routes/dashboard.storage'
import { Route as DashboardSqlRouteImport } from './routes/dashboard.sql'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardScalingRouteImport } from './routes/dashboard.scaling'
import { Route as DashboardRealtimeRouteImport } from './routes/dashboard.realtime'
import { Route as DashboardRbacRouteImport } from './routes/dashboard.rbac'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardObservabilityRouteImport } from './routes/dashboard.observability'
import { Route as DashboardMigrationsRouteImport } from './routes/dashboard.migrations'
import { Route as DashboardMfaRouteImport } from './routes/dashboard.mfa'
import { Route as DashboardLogsExplorerRouteImport } from './routes/dashboard.logs-explorer'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard.integrations'
import { Route as DashboardGraphqlRouteImport } from './routes/dashboard.graphql'
import { Route as DashboardFunctionsRouteImport } from './routes/dashboard.functions'
import { Route as DashboardEnterpriseRouteImport } from './routes/dashboard.enterprise'
import { Route as DashboardDevexRouteImport } from './routes/dashboard.devex'
import { Route as DashboardDatabaseRouteImport } from './routes/dashboard.database'
import { Route as DashboardBranchingRouteImport } from './routes/dashboard.branching'
import { Route as DashboardBackupsRouteImport } from './routes/dashboard.backups'
import { Route as DashboardAuditLogRouteImport } from './routes/dashboard.audit-log'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardApiRouteImport } from './routes/dashboard.api'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthPhoneRouteImport } from './routes/auth.phone'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth.confirm-email'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkspacesRoute = DashboardWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerifyRoute = DashboardVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVectorRoute = DashboardVectorRouteImport.update({
  id: '/vector',
  path: '/vector',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsageRoute = DashboardUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTokensRoute = DashboardTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSqlRoute = DashboardSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScalingRoute = DashboardScalingRouteImport.update({
  id: '/scaling',
  path: '/scaling',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRealtimeRoute = DashboardRealtimeRouteImport.update({
  id: '/realtime',
  path: '/realtime',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRbacRoute = DashboardRbacRouteImport.update({
  id: '/rbac',
  path: '/rbac',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObservabilityRoute = DashboardObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMigrationsRoute = DashboardMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMfaRoute = DashboardMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsExplorerRoute = DashboardLogsExplorerRouteImport.update({
  id: '/logs-explorer',
  path: '/logs-explorer',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGraphqlRoute = DashboardGraphqlRouteImport.update({
  id: '/graphql',
  path: '/graphql',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFunctionsRoute = DashboardFunctionsRouteImport.update({
  id: '/functions',
  path: '/functions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnterpriseRoute = DashboardEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevexRoute = DashboardDevexRouteImport.update({
  id: '/devex',
  path: '/devex',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabaseRoute = DashboardDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchingRoute = DashboardBranchingRouteImport.update({
  id: '/branching',
  path: '/branching',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackupsRoute = DashboardBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogRoute = DashboardAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiRoute = DashboardApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPhoneRoute = AuthPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/status': typeof StatusRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/functions': typeof DashboardFunctionsRoute
  '/dashboard/graphql': typeof DashboardGraphqlRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/logs-explorer': typeof DashboardLogsExplorerRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac': typeof DashboardRbacRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vector': typeof DashboardVectorRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/docs/api': typeof DocsApiRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/status': typeof StatusRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/functions': typeof DashboardFunctionsRoute
  '/dashboard/graphql': typeof DashboardGraphqlRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/logs-explorer': typeof DashboardLogsExplorerRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac': typeof DashboardRbacRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vector': typeof DashboardVectorRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/docs/api': typeof DocsApiRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/status': typeof StatusRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/phone': typeof AuthPhoneRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-log': typeof DashboardAuditLogRoute
  '/dashboard/backups': typeof DashboardBackupsRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/functions': typeof DashboardFunctionsRoute
  '/dashboard/graphql': typeof DashboardGraphqlRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/logs-explorer': typeof DashboardLogsExplorerRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/rbac': typeof DashboardRbacRoute
  '/dashboard/realtime': typeof DashboardRealtimeRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/dashboard/usage': typeof DashboardUsageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/vector': typeof DashboardVectorRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/docs/api': typeof DocsApiRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/status'
    | '/auth/confirm-email'
    | '/auth/forgot'
    | '/auth/phone'
    | '/auth/reset-password'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/audit-log'
    | '/dashboard/backups'
    | '/dashboard/branching'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/functions'
    | '/dashboard/graphql'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/logs-explorer'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/projects'
    | '/dashboard/rbac'
    | '/dashboard/realtime'
    | '/dashboard/scaling'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/tokens'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard/vector'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/docs/api'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/status'
    | '/auth/confirm-email'
    | '/auth/forgot'
    | '/auth/phone'
    | '/auth/reset-password'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/audit-log'
    | '/dashboard/backups'
    | '/dashboard/branching'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/functions'
    | '/dashboard/graphql'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/logs-explorer'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/projects'
    | '/dashboard/rbac'
    | '/dashboard/realtime'
    | '/dashboard/scaling'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/tokens'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard/vector'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/docs/api'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/status'
    | '/auth/confirm-email'
    | '/auth/forgot'
    | '/auth/phone'
    | '/auth/reset-password'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/audit-log'
    | '/dashboard/backups'
    | '/dashboard/branching'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/functions'
    | '/dashboard/graphql'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/logs-explorer'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/projects'
    | '/dashboard/rbac'
    | '/dashboard/realtime'
    | '/dashboard/scaling'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/tokens'
    | '/dashboard/usage'
    | '/dashboard/users'
    | '/dashboard/vector'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/docs/api'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  StatusRoute: typeof StatusRoute
  DocsApiRoute: typeof DocsApiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workspaces': {
      id: '/dashboard/workspaces'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces'
      preLoaderRoute: typeof DashboardWorkspacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verify': {
      id: '/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof DashboardVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vector': {
      id: '/dashboard/vector'
      path: '/vector'
      fullPath: '/dashboard/vector'
      preLoaderRoute: typeof DashboardVectorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/usage': {
      id: '/dashboard/usage'
      path: '/usage'
      fullPath: '/dashboard/usage'
      preLoaderRoute: typeof DashboardUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tokens': {
      id: '/dashboard/tokens'
      path: '/tokens'
      fullPath: '/dashboard/tokens'
      preLoaderRoute: typeof DashboardTokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sql': {
      id: '/dashboard/sql'
      path: '/sql'
      fullPath: '/dashboard/sql'
      preLoaderRoute: typeof DashboardSqlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scaling': {
      id: '/dashboard/scaling'
      path: '/scaling'
      fullPath: '/dashboard/scaling'
      preLoaderRoute: typeof DashboardScalingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/realtime': {
      id: '/dashboard/realtime'
      path: '/realtime'
      fullPath: '/dashboard/realtime'
      preLoaderRoute: typeof DashboardRealtimeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rbac': {
      id: '/dashboard/rbac'
      path: '/rbac'
      fullPath: '/dashboard/rbac'
      preLoaderRoute: typeof DashboardRbacRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/observability': {
      id: '/dashboard/observability'
      path: '/observability'
      fullPath: '/dashboard/observability'
      preLoaderRoute: typeof DashboardObservabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/migrations': {
      id: '/dashboard/migrations'
      path: '/migrations'
      fullPath: '/dashboard/migrations'
      preLoaderRoute: typeof DashboardMigrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mfa': {
      id: '/dashboard/mfa'
      path: '/mfa'
      fullPath: '/dashboard/mfa'
      preLoaderRoute: typeof DashboardMfaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs-explorer': {
      id: '/dashboard/logs-explorer'
      path: '/logs-explorer'
      fullPath: '/dashboard/logs-explorer'
      preLoaderRoute: typeof DashboardLogsExplorerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/graphql': {
      id: '/dashboard/graphql'
      path: '/graphql'
      fullPath: '/dashboard/graphql'
      preLoaderRoute: typeof DashboardGraphqlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/functions': {
      id: '/dashboard/functions'
      path: '/functions'
      fullPath: '/dashboard/functions'
      preLoaderRoute: typeof DashboardFunctionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enterprise': {
      id: '/dashboard/enterprise'
      path: '/enterprise'
      fullPath: '/dashboard/enterprise'
      preLoaderRoute: typeof DashboardEnterpriseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devex': {
      id: '/dashboard/devex'
      path: '/devex'
      fullPath: '/dashboard/devex'
      preLoaderRoute: typeof DashboardDevexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/database': {
      id: '/dashboard/database'
      path: '/database'
      fullPath: '/dashboard/database'
      preLoaderRoute: typeof DashboardDatabaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branching': {
      id: '/dashboard/branching'
      path: '/branching'
      fullPath: '/dashboard/branching'
      preLoaderRoute: typeof DashboardBranchingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/backups': {
      id: '/dashboard/backups'
      path: '/backups'
      fullPath: '/dashboard/backups'
      preLoaderRoute: typeof DashboardBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit-log': {
      id: '/dashboard/audit-log'
      path: '/audit-log'
      fullPath: '/dashboard/audit-log'
      preLoaderRoute: typeof DashboardAuditLogRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api': {
      id: '/dashboard/api'
      path: '/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof DashboardApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/phone': {
      id: '/auth/phone'
      path: '/phone'
      fullPath: '/auth/phone'
      preLoaderRoute: typeof AuthPhoneRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthPhoneRoute: typeof AuthPhoneRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthPhoneRoute: AuthPhoneRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardApiRoute: typeof DashboardApiRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardAuditLogRoute: typeof DashboardAuditLogRoute
  DashboardBackupsRoute: typeof DashboardBackupsRoute
  DashboardBranchingRoute: typeof DashboardBranchingRoute
  DashboardDatabaseRoute: typeof DashboardDatabaseRoute
  DashboardDevexRoute: typeof DashboardDevexRoute
  DashboardEnterpriseRoute: typeof DashboardEnterpriseRoute
  DashboardFunctionsRoute: typeof DashboardFunctionsRoute
  DashboardGraphqlRoute: typeof DashboardGraphqlRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardLogsExplorerRoute: typeof DashboardLogsExplorerRoute
  DashboardMfaRoute: typeof DashboardMfaRoute
  DashboardMigrationsRoute: typeof DashboardMigrationsRoute
  DashboardObservabilityRoute: typeof DashboardObservabilityRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardRbacRoute: typeof DashboardRbacRoute
  DashboardRealtimeRoute: typeof DashboardRealtimeRoute
  DashboardScalingRoute: typeof DashboardScalingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSqlRoute: typeof DashboardSqlRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardTokensRoute: typeof DashboardTokensRoute
  DashboardUsageRoute: typeof DashboardUsageRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardVectorRoute: typeof DashboardVectorRoute
  DashboardVerifyRoute: typeof DashboardVerifyRoute
  DashboardWorkspacesRoute: typeof DashboardWorkspacesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardApiRoute: DashboardApiRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardAuditLogRoute: DashboardAuditLogRoute,
  DashboardBackupsRoute: DashboardBackupsRoute,
  DashboardBranchingRoute: DashboardBranchingRoute,
  DashboardDatabaseRoute: DashboardDatabaseRoute,
  DashboardDevexRoute: DashboardDevexRoute,
  DashboardEnterpriseRoute: DashboardEnterpriseRoute,
  DashboardFunctionsRoute: DashboardFunctionsRoute,
  DashboardGraphqlRoute: DashboardGraphqlRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardLogsExplorerRoute: DashboardLogsExplorerRoute,
  DashboardMfaRoute: DashboardMfaRoute,
  DashboardMigrationsRoute: DashboardMigrationsRoute,
  DashboardObservabilityRoute: DashboardObservabilityRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardRbacRoute: DashboardRbacRoute,
  DashboardRealtimeRoute: DashboardRealtimeRoute,
  DashboardScalingRoute: DashboardScalingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSqlRoute: DashboardSqlRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardTokensRoute: DashboardTokensRoute,
  DashboardUsageRoute: DashboardUsageRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardVectorRoute: DashboardVectorRoute,
  DashboardVerifyRoute: DashboardVerifyRoute,
  DashboardWorkspacesRoute: DashboardWorkspacesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  StatusRoute: StatusRoute,
  DocsApiRoute: DocsApiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
