/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWorkspacesRouteImport } from './routes/dashboard.workspaces'
import { Route as DashboardVerifyRouteImport } from './routes/dashboard.verify'
import { Route as DashboardUsersRouteImport } from './routes/dashboard.users'
import { Route as DashboardStorageRouteImport } from './routes/dashboard.storage'
import { Route as DashboardSqlRouteImport } from './routes/dashboard.sql'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardScalingRouteImport } from './routes/dashboard.scaling'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardObservabilityRouteImport } from './routes/dashboard.observability'
import { Route as DashboardMigrationsRouteImport } from './routes/dashboard.migrations'
import { Route as DashboardMfaRouteImport } from './routes/dashboard.mfa'
import { Route as DashboardLogsRouteImport } from './routes/dashboard.logs'
import { Route as DashboardJobsRouteImport } from './routes/dashboard.jobs'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard.integrations'
import { Route as DashboardEnterpriseRouteImport } from './routes/dashboard.enterprise'
import { Route as DashboardDevexRouteImport } from './routes/dashboard.devex'
import { Route as DashboardDatabaseRouteImport } from './routes/dashboard.database'
import { Route as DashboardBranchingRouteImport } from './routes/dashboard.branching'
import { Route as DashboardAuditRouteImport } from './routes/dashboard.audit'
import { Route as DashboardApiRouteImport } from './routes/dashboard.api'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspacesRoute = DashboardWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVerifyRoute = DashboardVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSqlRoute = DashboardSqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScalingRoute = DashboardScalingRouteImport.update({
  id: '/scaling',
  path: '/scaling',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardObservabilityRoute = DashboardObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMigrationsRoute = DashboardMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMfaRoute = DashboardMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnterpriseRoute = DashboardEnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevexRoute = DashboardDevexRouteImport.update({
  id: '/devex',
  path: '/devex',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDatabaseRoute = DashboardDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBranchingRoute = DashboardBranchingRouteImport.update({
  id: '/branching',
  path: '/branching',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiRoute = DashboardApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/api': typeof DashboardApiRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/branching': typeof DashboardBranchingRoute
  '/dashboard/database': typeof DashboardDatabaseRoute
  '/dashboard/devex': typeof DashboardDevexRoute
  '/dashboard/enterprise': typeof DashboardEnterpriseRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/jobs': typeof DashboardJobsRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/mfa': typeof DashboardMfaRoute
  '/dashboard/migrations': typeof DashboardMigrationsRoute
  '/dashboard/observability': typeof DashboardObservabilityRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/scaling': typeof DashboardScalingRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/sql': typeof DashboardSqlRoute
  '/dashboard/storage': typeof DashboardStorageRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/verify': typeof DashboardVerifyRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/branching'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/projects'
    | '/dashboard/scaling'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/users'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/branching'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/projects'
    | '/dashboard/scaling'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/users'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/ai'
    | '/dashboard/api'
    | '/dashboard/audit'
    | '/dashboard/branching'
    | '/dashboard/database'
    | '/dashboard/devex'
    | '/dashboard/enterprise'
    | '/dashboard/integrations'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/mfa'
    | '/dashboard/migrations'
    | '/dashboard/observability'
    | '/dashboard/projects'
    | '/dashboard/scaling'
    | '/dashboard/settings'
    | '/dashboard/sql'
    | '/dashboard/storage'
    | '/dashboard/users'
    | '/dashboard/verify'
    | '/dashboard/workspaces'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workspaces': {
      id: '/dashboard/workspaces'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces'
      preLoaderRoute: typeof DashboardWorkspacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/verify': {
      id: '/dashboard/verify'
      path: '/verify'
      fullPath: '/dashboard/verify'
      preLoaderRoute: typeof DashboardVerifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/storage': {
      id: '/dashboard/storage'
      path: '/storage'
      fullPath: '/dashboard/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sql': {
      id: '/dashboard/sql'
      path: '/sql'
      fullPath: '/dashboard/sql'
      preLoaderRoute: typeof DashboardSqlRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scaling': {
      id: '/dashboard/scaling'
      path: '/scaling'
      fullPath: '/dashboard/scaling'
      preLoaderRoute: typeof DashboardScalingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/observability': {
      id: '/dashboard/observability'
      path: '/observability'
      fullPath: '/dashboard/observability'
      preLoaderRoute: typeof DashboardObservabilityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/migrations': {
      id: '/dashboard/migrations'
      path: '/migrations'
      fullPath: '/dashboard/migrations'
      preLoaderRoute: typeof DashboardMigrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mfa': {
      id: '/dashboard/mfa'
      path: '/mfa'
      fullPath: '/dashboard/mfa'
      preLoaderRoute: typeof DashboardMfaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enterprise': {
      id: '/dashboard/enterprise'
      path: '/enterprise'
      fullPath: '/dashboard/enterprise'
      preLoaderRoute: typeof DashboardEnterpriseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/devex': {
      id: '/dashboard/devex'
      path: '/devex'
      fullPath: '/dashboard/devex'
      preLoaderRoute: typeof DashboardDevexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/database': {
      id: '/dashboard/database'
      path: '/database'
      fullPath: '/dashboard/database'
      preLoaderRoute: typeof DashboardDatabaseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/branching': {
      id: '/dashboard/branching'
      path: '/branching'
      fullPath: '/dashboard/branching'
      preLoaderRoute: typeof DashboardBranchingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api': {
      id: '/dashboard/api'
      path: '/api'
      fullPath: '/dashboard/api'
      preLoaderRoute: typeof DashboardApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardApiRoute: typeof DashboardApiRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardBranchingRoute: typeof DashboardBranchingRoute
  DashboardDatabaseRoute: typeof DashboardDatabaseRoute
  DashboardDevexRoute: typeof DashboardDevexRoute
  DashboardEnterpriseRoute: typeof DashboardEnterpriseRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMfaRoute: typeof DashboardMfaRoute
  DashboardMigrationsRoute: typeof DashboardMigrationsRoute
  DashboardObservabilityRoute: typeof DashboardObservabilityRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardScalingRoute: typeof DashboardScalingRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSqlRoute: typeof DashboardSqlRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardVerifyRoute: typeof DashboardVerifyRoute
  DashboardWorkspacesRoute: typeof DashboardWorkspacesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardApiRoute: DashboardApiRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardBranchingRoute: DashboardBranchingRoute,
  DashboardDatabaseRoute: DashboardDatabaseRoute,
  DashboardDevexRoute: DashboardDevexRoute,
  DashboardEnterpriseRoute: DashboardEnterpriseRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMfaRoute: DashboardMfaRoute,
  DashboardMigrationsRoute: DashboardMigrationsRoute,
  DashboardObservabilityRoute: DashboardObservabilityRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardScalingRoute: DashboardScalingRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSqlRoute: DashboardSqlRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardVerifyRoute: DashboardVerifyRoute,
  DashboardWorkspacesRoute: DashboardWorkspacesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
